services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      # The HTTP Port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - servitnet
    depends_on:
      - mongoDB

  userfrontend:
    build: ./UserFrontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usermenu.rule=Host(`dinebuddy.in`) && PathPrefix(`/user/menu`)"
      - "traefik.http.routers.usermenu.entrypoints=web"
      - "traefik.http.routers.usermenu.priority=10"
      - "traefik.http.services.usermenu.loadbalancer.server.port=5173"
    ports:
      - "5173:5173"
    networks:
      - servitnet

  adminfrontend:
    build: ./AdminFrontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.guestbook.rule=Host(`dinebuddy.in`)"
      - "traefik.http.routers.guestbook.entrypoints=web"
      - "traefik.http.services.guestbook.loadbalancer.server.port=5175"
    ports:
      - "5175:5175"
    networks:
      - servitnet

  mongoDB:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - servitnet
    volumes:
      - mongo-data:/data/db

networks:
  servitnet:
    driver: bridge

volumes:
  mongo-data:
    driver: local
