services:
  reverse-proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=hellodinebuddy@gmail.com"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./letsencrypt:/letsencrypt
    networks:
      - servitnet 

  backend:
    build: ./backend
    networks:
      - servitnet
    depends_on:
      - mongoDB

  userfrontend:
    build: ./UserFrontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.usermenu.rule=Host(`dinebuddy.in`) && PathPrefix(`/user/menu`)"
      - "traefik.http.routers.usermenu.entrypoints=websecure"
      - "traefik.http.routers.usermenu.priority=10"
      - "traefik.http.routers.usermenu.tls.certresolver=le"
      - "traefik.http.services.usermenu.loadbalancer.server.port=5173"
    networks:
      - servitnet

  adminfrontend:
    build: ./AdminFrontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminrouter.rule=Host(`dinebuddy.in`)"
      - "traefik.http.routers.adminrouter.entrypoints=websecure"
      - "traefik.http.routers.adminrouter.tls.certresolver=le"
      - "traefik.http.services.adminrouter.loadbalancer.server.port=5175"
    networks:
      - servitnet

  mongoDB:
    image: mongo:latest
    networks:
      - servitnet
    volumes:
      - mongo-data:/data/db

networks:
  servitnet:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  letsencrypt:
